name: Main
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.13.x"
          - "1.14.x"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1.1.2
        with:
          go-version: ${{matrix.go}}
      - name: Check out code
        uses: actions/checkout@v2.1.0
      - name: Download modules
        run: go mod download
      - name: Test
        run: go test -v --coverprofile=cover.out ./...
      - name: Upload coverage profile
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: cover.out
